// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPF4lHmqzEVofNosVMBddV4tJY13SA6fs',
    appId: '1:288626336136:web:a66ae9823c76ee88d55a3d',
    messagingSenderId: '288626336136',
    projectId: 'king-nexus',
    authDomain: 'king-nexus.firebaseapp.com',
    storageBucket: 'king-nexus.firebasestorage.app',
    measurementId: 'G-9Y91D3DGR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM4EIo9Le-jAuRRckt1fgMn2XqV9b9NPs',
    appId: '1:288626336136:android:6b0680efab3c7cf3d55a3d',
    messagingSenderId: '288626336136',
    projectId: 'king-nexus',
    storageBucket: 'king-nexus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiqAQlpr7auMi_YPx1SP1X3eTM_Aj4Q3Q',
    appId: '1:288626336136:ios:ff1ae89a15ca93bad55a3d',
    messagingSenderId: '288626336136',
    projectId: 'king-nexus',
    storageBucket: 'king-nexus.firebasestorage.app',
    iosBundleId: 'com.example.kingNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiqAQlpr7auMi_YPx1SP1X3eTM_Aj4Q3Q',
    appId: '1:288626336136:ios:ff1ae89a15ca93bad55a3d',
    messagingSenderId: '288626336136',
    projectId: 'king-nexus',
    storageBucket: 'king-nexus.firebasestorage.app',
    iosBundleId: 'com.example.kingNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPF4lHmqzEVofNosVMBddV4tJY13SA6fs',
    appId: '1:288626336136:web:1dc40d958101b2c4d55a3d',
    messagingSenderId: '288626336136',
    projectId: 'king-nexus',
    authDomain: 'king-nexus.firebaseapp.com',
    storageBucket: 'king-nexus.firebasestorage.app',
    measurementId: 'G-NJGPCVDGC7',
  );
}
